name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Java setup
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build Backend
        working-directory: Task_Management
        run: mvn clean install

      # Node setup
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Frontend
        working-directory: task-frontened
        run: |
          npm install
          npm run build

      - name: Build Docker Images
        run: |
          docker build -t backend ./Task_Management
          docker build -t frontend ./task-frontened